#include "defs.h"


#define RENDERER_CMP_LESS		D3DCMP_LESS 
#define RENDERER_CMP_LEQUAL		D3DCMP_LESSEQUAL
#define RENDERER_CMP_EQUAL		D3DCMP_EQUAL
#define RENDERER_CMP_GREATER	D3DCMP_GREATER 
#define RENDERER_CMP_GEQUAL		D3DCMP_GREATEREQUAL

#define RENDERER_BLEND_OP_ADD	D3DBLENDOP_ADD
#define RENDERER_BLEND_OP_SUB	D3DBLENDOP_SUBTRACT 

#define RENDERER_BLEND_ONE		D3DBLEND_ONE
#define RENDERER_BLEND_ZERO		D3DBLEND_ZERO
#define RENDERER_BLEND_SRC_ALPHA	D3DBLEND_SRCALPHA
#define RENDERER_BLEND_SRC_INVALPHA	D3DBLEND_INVSRCALPHA 
#define RENDERER_BLEND_DEST_ALPHA	D3DBLEND_DESTALPHA
#define RENDERER_BLEND_DEST_INVALPHA	D3DBLEND_INVDESTALPHA 

#define RENDERER_CULL_NONE		D3DCULL_NONE
#define RENDERER_CULL_FRONT		D3DCULL_CW
#define RENDERER_CULL_BACK		D3DCULL_CCW 

#define RENDERER_TEXF_NONE		D3DTEXF_NONE 
#define RENDERER_TEXF_NEAREST	D3DTEXF_POINT
#define RENDERER_TEXF_LINEAR	D3DTEXF_LINEAR
#define RENDERER_TEXF_ANISO		D3DTEXF_ANISOTROPIC

#define RENDERER_TEXM_WARP		D3DTADDRESS_WRAP 
#define RENDERER_TEXM_CLAMP	    D3DTADDRESS_MIRROR 
#define RENDERER_TEXM_MIRROR	D3DTADDRESS_CLAMP


#define BUFFER_TYPE_VERTEX		0
#define BUFFER_TYPE_INDEX		1


#define TEX_FMT_RGB8            D3DFMT_R8G8B8
#define TEX_FMT_ARGB8           D3DFMT_A8R8G8B8
#define TEX_FMT_A2RGB10         D3DFMT_A2R10G10B10

#define TEX_FMT_D16             D3DFMT_D16
#define TEX_FMT_D24S8           D3DFMT_D24S8
#define TEX_FMT_D32             D3DFMT_D32

#define TEX_FMT_R16F            D3DFMT_R16F
#define TEX_FMT_GR16F           D3DFMT_G16R16F 
#define TEX_FMT_ABGR16F         D3DFMT_A16B16G16R16F

#define TEX_FMT_R32F            D3DFMT_R32F
#define TEX_FMT_GR32F           D3DFMT_G32R32F 
#define TEX_FMT_ABGR32F         D3DFMT_A32B32G32R32F